const { erroHttp, validarId } = require('./projetos');
function admin(req){if(!['proprietario','administrador','superadministrador'].includes(req.marcenaria.papel))throw erroHttp(403,'Somente administradores podem alterar automações.');}
function registrarAutomacoes(app,banco,rota){
 app.get('/api/automacoes',rota(async(req,res)=>{const campos=(await banco.query('SELECT id,nome,obrigatorio FROM campos_personalizados WHERE marcenaria_id=$1 ORDER BY id',[req.marcenaria.id])).rows;const lembrete=(await banco.query('SELECT ativo,horas_espera FROM lembrete_configuracoes WHERE marcenaria_id=$1',[req.marcenaria.id])).rows[0]||{ativo:false,horas_espera:24};res.json({campos,lembrete});}));
 app.put('/api/automacoes',rota(async(req,res)=>{admin(req);const campos=Array.isArray(req.body?.campos)?req.body.campos:[];if(campos.length>12)throw erroHttp(400,'Use no máximo 12 campos personalizados.');const limpos=campos.map(c=>({nome:String(c.nome||'').trim(),obrigatorio:c.obrigatorio===true}));if(limpos.some(c=>!c.nome||c.nome.length>80)||new Set(limpos.map(c=>c.nome.toLowerCase())).size!==limpos.length)throw erroHttp(400,'Revise os nomes dos campos personalizados.');const ativo=req.body?.lembrete?.ativo===true;const horas=Number(req.body?.lembrete?.horas_espera||24);if(!Number.isInteger(horas)||horas<6||horas>168)throw erroHttp(400,'Escolha entre 6 e 168 horas para o lembrete.');const db=await banco.connect();try{await db.query('BEGIN');await db.query('DELETE FROM campos_personalizados WHERE marcenaria_id=$1',[req.marcenaria.id]);for(const c of limpos)await db.query('INSERT INTO campos_personalizados (marcenaria_id,nome,obrigatorio) VALUES ($1,$2,$3)',[req.marcenaria.id,c.nome,c.obrigatorio]);await db.query('INSERT INTO lembrete_configuracoes (marcenaria_id,ativo,horas_espera) VALUES ($1,$2,$3) ON CONFLICT (marcenaria_id) DO UPDATE SET ativo=EXCLUDED.ativo,horas_espera=EXCLUDED.horas_espera,atualizado_em=CURRENT_TIMESTAMP',[req.marcenaria.id,ativo,horas]);await db.query('COMMIT');res.json({mensagem:'Automações salvas.'});}catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}));
 app.put('/api/projetos/:id/atendimento-humano',rota(async(req,res)=>{admin(req);const id=validarId(req.params.id),ativo=req.body?.ativo===true;const p=(await banco.query('UPDATE projetos SET atendimento_humano=$1,atualizado_em=CURRENT_TIMESTAMP WHERE id=$2 AND marcenaria_id=$3 RETURNING id',[ativo,id,req.marcenaria.id])).rows[0];if(!p)throw erroHttp(404,'Projeto não encontrado.');res.json({ativo,mensagem:ativo?'Atendimento humano assumido. A Suzy não responderá novas mensagens deste projeto.':'A Suzy voltou a acompanhar este projeto.'});}));
 app.put('/api/projetos/:id/prioridade',rota(async(req,res)=>{admin(req);const id=validarId(req.params.id),prioridade=String(req.body?.prioridade||'');if(!['baixa','normal','alta'].includes(prioridade))throw erroHttp(400,'Prioridade inválida.');const p=(await banco.query('UPDATE projetos SET prioridade=$1,atualizado_em=CURRENT_TIMESTAMP WHERE id=$2 AND marcenaria_id=$3 RETURNING id',[prioridade,id,req.marcenaria.id])).rows[0];if(!p)throw erroHttp(404,'Projeto não encontrado.');res.json({prioridade});}));
}
module.exports={registrarAutomacoes};
