ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS usuario VARCHAR(80);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS superadministrador BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS trocar_senha BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS usuarios_usuario_uq ON usuarios (lower(usuario)) WHERE usuario IS NOT NULL;
