ALTER TABLE projetos ADD COLUMN IF NOT EXISTS atendimento_humano BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS prioridade VARCHAR(12) NOT NULL DEFAULT 'normal' CHECK (prioridade IN ('baixa','normal','alta'));
ALTER TABLE projetos ADD COLUMN IF NOT EXISTS lembrete_enviado_em TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS campos_personalizados (
  id BIGSERIAL PRIMARY KEY, marcenaria_id INTEGER NOT NULL REFERENCES marcenarias(id) ON DELETE CASCADE,
  nome VARCHAR(80) NOT NULL, obrigatorio BOOLEAN NOT NULL DEFAULT FALSE, criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (marcenaria_id,nome)
);
CREATE TABLE IF NOT EXISTS lembrete_configuracoes (
  marcenaria_id INTEGER PRIMARY KEY REFERENCES marcenarias(id) ON DELETE CASCADE,
  ativo BOOLEAN NOT NULL DEFAULT FALSE, horas_espera INTEGER NOT NULL DEFAULT 24 CHECK (horas_espera BETWEEN 6 AND 168), atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
